version: "3.9"

services:
    web:
      image: osscore/osscore:2.0
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./uploads:/code/uploads
      ports:
        - "8000:8000"
    redis:
      image: redis
      ports: 
        - "6379:6379"
    celery:
      restart: always
      image: osscore/osscore:2.0
      volumes: 
        - ./uploads:/code/uploads
      command: celery -A OSSCore.celery worker --loglevel=INFO --pool=solo
      depends_on:
        - redis
        - web
